name: Development
on:
  workflow_dispatch: {}
  push:
    branches:
      - cloudFront    
jobs:
  generate-docs:
    uses: ./.github/workflows/generate-docs.yml
    permissions:
      contents: write
      pull-requests: read
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  deploy-cdk-to-development:
    needs: generate-docs
    uses: ./.github/workflows/cdk.yml
    permissions:
      id-token: write   
      contents: read
    with:
      PROJECT_ENVIRONMENT: development
      AWS_REGION: us-east-1
      WORKING_DIR: deploy/cdk
      GIT_HASH: ${{ github.sha }}
  get-cloudfront-id:
    needs: deploy-cdk-to-development
    runs-on: ubuntu-latest
    permissions:               
      id-token: write          
      contents: read
    outputs:
      dist_id: ${{ steps.get_dist_id.outputs.dist_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267230957:role/git-action
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Get CloudFront Distribution ID from CDK Export
        id: get_dist_id
        run: |
          DIST_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='jsdocs-development-DistributionId'].Value" \
            --output text)
          echo "dist_id=$DIST_ID" >> $GITHUB_OUTPUT

  deploy-to-s3:
    needs: get-cloudfront-id
    uses: ./.github/workflows/s3.yml
    permissions:
      id-token: write 
      contents: read
    with:
      PROJECT_ENVIRONMENT: development
      AWS_REGION: us-east-1
      AWS_BUCKET: silo-jsdocs-development
      PROJECT_NAME: jsdocs
      CLOUDFRONT_DIST_ID: ${{ needs.get-cloudfront-id.outputs.dist_id }}
  
            
